[package]

name = "regex"
version = "0.1.5"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/regex"
documentation = "http://doc.rust-lang.org/regex"
homepage = "https://github.com/rust-lang/regex"
description = """
An implementation of regular expressions for Rust.
"""

[[test]]
path = "tests/mod.rs"
name = "all"

[dev-dependencies.regex_macros]
path = "regex_macros"
version = "0.1.0"
